# Exercícios NumPy  

Agora que aprendemos sobre NumPy, vamos testar seu conhecimento. Começaremos com algumas tarefas simples, para depois entrarmos nas perguntas mais complicadas.

#### Importe NumPy como np

In [1]:
import numpy as np

#### Crie uma matriz de 10 zeros

In [4]:
matriz_10zeros = np.zeros(10)
matriz_10zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Crie uma matriz de 10 ones

In [11]:
matriz_10ones = np.ones(10)
matriz_10ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Crie uma matriz de 10 cincos

In [13]:
matriz_10cincos = matriz_10zeros + 5
matriz_10cincos

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### Crie um array de inteiros de 10 até 50

In [81]:
array10inteiros_dez_ciquenta = np.arange(10,51)
array10inteiros_dez_ciquenta

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Crie um array dos numeros pares de 10 até 50

In [82]:
arraypares_dez_cinquenta = np.arange(10,51,2)
arraypares_dez_cinquenta

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### Criei uma matriz 3x3 com valores variando de 0 até 8

In [83]:
arr_3_3_zero_oito = np.arange(9)
matriz_3_3 = arr_3_3_zero_oito.reshape(3,3)
matriz_3_3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Crie uma matriz identidade 3x3

In [24]:
matriz_identidade_3_3 = np.eye(3)
matriz_identidade_3_3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Use NumPy para gerar números aleatórios entre 0 e 1

In [30]:
num_aleatorio_0_1 = np.random.rand(1)
num_aleatorio_0_1

array([0.05593212])

#### Use Numpy para gerar um array de 25 números aleatórios tirados de uma distribuição normal.

In [31]:
arr_25_normal = np.random.randn(25)
arr_25_normal

array([ 0.10007206, -1.06528219,  1.46002124, -1.45430265, -1.12754006,
       -0.23549523, -0.02607307,  0.20387615, -1.41533676,  0.72024115,
       -1.0562524 ,  2.08447821, -1.20538744,  0.18216914,  1.25797559,
        0.68483522, -0.58947958, -0.51303731, -1.01062187, -0.70263278,
        0.10995882,  0.1194372 ,  0.59678509,  0.78194204,  1.04677762])

#### Crie a seguinte matriz:

In [43]:
matriz_10_10_zero_100_div_100 = np.arange(1,101).reshape(10,10) / 100
matriz_10_10_zero_100_div_100

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

#### Crie um array de tamanho 20 igualmente espaçado entre 0 e 1.

In [45]:
arr_20_zero_um = np.linspace(0,1,20)
arr_20_zero_um

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Indexação Numpy e Seleção

Agora você receberá algumas matrizes e será solicitado a replicar as saídas resultantes da matriz:

In [50]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [51]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [61]:
condition = mat == 20
mat[condition][0]

20

20

In [72]:
mat[:3,1].reshape(3,1)

array([[ 2],
       [ 7],
       [12]])

array([[ 2],
       [ 7],
       [12]])

In [74]:
mat[4]

array([21, 22, 23, 24, 25])

array([21, 22, 23, 24, 25])

In [76]:
mat[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Agora faça o seguinte

#### Obter a soma de todos os valores no "mat"

In [77]:
np.sum(mat)

325

#### Obter o desvio padrão dos valores em mat

In [78]:
np.std(mat)

7.211102550927978

#### Obter a soma de todas as colunas em mat

In [85]:
mat.sum(axis = 0)

array([55, 60, 65, 70, 75])