# Criação de Vetores e Arrays com Numpy


In [ ]:
import numpy as np

In [ ]:
minha_lista = [1,2,3]

In [ ]:
minha_lista

[1, 2, 3]

In [ ]:
np.array(minha_lista)

array([1, 2, 3])

In [ ]:
minha_matriz = [[1,2,3], [4,5,6], [7,8,9]]

In [ ]:
np.array(minha_matriz)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [ ]:
np.zeros(3)

array([0., 0., 0.])

In [ ]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.linspace(0,10,2)

array([ 0., 10.])

In [ ]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [ ]:
np.random.rand(5)

array([0.31682503, 0.11304368, 0.40972032, 0.20281234, 0.40722288])

In [ ]:
np.random.rand(5)*100

array([59.22565107, 33.37534239, 89.65839466, 36.96083928,  1.13366164])

In [ ]:
np.random.randn(5)

array([-1.45755258, -1.03347921,  0.02297922, -0.35970005,  0.68167929])

In [ ]:
np.random.randint(0,100,10)

array([36,  3, 33, 93, 87, 57, 24, 77,  4, 29])

In [ ]:
arr = np.random.randint(0,100,25)

In [ ]:
arr = arr.reshape((5,5))

In [ ]:
arr

array([[29, 67, 60, 97, 35],
       [ 0, 45,  7, 77, 50],
       [54, 49, 87, 65,  1],
       [ 4, 95, 66, 52, 70],
       [53, 56, 56, 22, 63]])

In [ ]:
arr.max()

97

In [ ]:
arr.argmax()

3

# Indexação e Fatiamento de arrays

In [ ]:
arr = np.arange(0,30,3)

In [ ]:
arr[3]

9

In [ ]:
arr[2:5]

array([ 6,  9, 12])

In [ ]:
arr[5:]

array([15, 18, 21, 24, 27])

In [ ]:
arr[5:] = 100

In [ ]:
arr

array([  0,   3,   6,   9,  12, 100, 100, 100, 100, 100])

In [ ]:
arr = np.arange(50).reshape((5,10))
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [ ]:
arr[:3][:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [ ]:
arr[1:4,3:5]

array([[13, 14],
       [23, 24],
       [33, 34]])

In [ ]:
eh_maior_que_dez = arr > 10
arr[eh_maior_que_dez]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
       28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44,
       45, 46, 47, 48, 49])

# Operações com Numpy Arrays

In [ ]:
arr = np.arange(0,16)

In [ ]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [ ]:
arr*arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225])

In [ ]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
arr**5

array([     0,      1,     32,    243,   1024,   3125,   7776,  16807,
        32768,  59049, 100000, 161051, 248832, 371293, 537824, 759375])

In [ ]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115])

In [ ]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335])

In [ ]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04,
       1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06])

In [ ]:
np.mean(arr)

7.5

In [ ]:
np.std(arr)

4.6097722286464435

In [ ]:
np.max(arr)

15

In [ ]:
np.min(arr)

0

In [ ]:
arr.max()

15

In [ ]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111, -0.99999021, -0.53657292,  0.42016704,  0.99060736,
        0.65028784])

In [ ]:
np.sin(arr*2)

array([ 0.        ,  0.90929743, -0.7568025 , -0.2794155 ,  0.98935825,
       -0.54402111, -0.53657292,  0.99060736, -0.28790332, -0.75098725,
        0.91294525, -0.00885131, -0.90557836,  0.76255845,  0.27090579,
       -0.98803162])